version: '3.9'
services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
    #image: yidadaa/chatgpt-next-web
    image: registry.cn-hangzhou.aliyuncs.com/sijinhui/chatgpt-next-web
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:23000:3000"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - AZURE_URL=$AZURE_URL
      - AZURE_KEY=$AZURE_KEY
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
    networks:
      - chatgpt-ns

networks:
  chatgpt-ns:
    external: true